# Generated by Django 2.2.14 on 2020-11-22 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Nombre Clase')),
                ('aforo', models.IntegerField(null=True, verbose_name='Aforo')),
                ('duration', models.IntegerField(null=True, verbose_name='Total horas')),
                ('estado', models.BooleanField(default=False, verbose_name='Activo/Inactivo')),
            ],
            options={
                'verbose_name': 'Asignatura',
                'verbose_name_plural': 'Asignaturas',
                'ordering': ['name'],
            },
        ),
    ]
