# Generated by Django 2.2.14 on 2020-11-23 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignatura', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignatura',
            name='name_students',
            field=models.TextField(null=True),
        ),
    ]
