# Generated by Django 2.2.14 on 2020-11-23 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asignatura', '0003_auto_20201123_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignatura',
            name='name_students',
        ),
    ]
