# Generated by Django 2.2.14 on 2020-11-29 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesores', '0001_initial'),
        ('asignatura', '0004_remove_asignatura_name_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignatura',
            name='profesores',
            field=models.ManyToManyField(related_name='profesores', to='profesores.Profesor'),
        ),
    ]
