# Generated by Django 2.2.14 on 2020-11-29 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignatura', '0005_asignatura_profesores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignatura',
            name='profesores',
            field=models.ManyToManyField(related_name='asignaturas', to='profesores.Profesor'),
        ),
    ]
