# Generated by Django 2.2.14 on 2020-11-23 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0002_estudiante_asignatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='clase',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
