# Generated by Django 2.2.14 on 2020-11-29 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, verbose_name='Nombre Clase')),
                ('direccion', models.IntegerField(null=True)),
                ('telefono', models.IntegerField(null=True)),
            ],
        ),
    ]
